const restricoesBase = {
    area_rLoja: false,
    area_rBar: false,
    area_rDelivery: false,
    area_rGiral: false,
    area_rExterna: false,
    area_rRecepcao: false,
    abrirMesa: false,
    loginSistema: false,
    loginSistema: false,
    loginSistemaSempreOn: false,
    loginSistemaAdm: false,
    loginSistemaCozinha: false,
    loginSistemaRecepcao: false,
    loginSistemaManutencao: false,
    imprimirMesa: false,
    mesaComandarItem: false,

    r_cadastrarFila: false,
    r_cadastrarClienteFila: false,
    r_chamarClienteFila: false,
    r_cadastrarCliente: false,
    r_alterarCliente: false,
    r_alterarFila: false,
    r_cadastrarPrioridade: false,

    c_caixa_cancelamento: false,
    c_caixa_receber: false,
    c_caixa_desconto: false,
    c_caixa_cobrar: false,
    c_comanda_alterarGorjeta: false,
    c_comanda_RemoverGorjeta: false,
    c_caixa_operador: false,
    c_caixa_fecharCaixa: false,
    c_caixa_abrirCaixa: false,
    c_caixa_gavetaCaixa: false,
    c_caixa_retiradaCaixa: false,
    c_cadastrar_entregador: false,


    m_ComandaTransfere: false,
    m_ComandaDivide: false,
    m_AreaComandaTransfere: false,
    m_iniciarOperacao: false,
    m_controleIluminacao: false,
    m_controleVentilacao: false,
    m_controleAcessos: false,
    m_visualizarCameras: false,

    g_controleCameras: false,
    g_cadastrarColaborador: false,
    g_caixa_operador: false,
    g_comandaZeradaCancelar: false,
    g_comandaCancelamento: false,
    g_maitre_abrirMesa: false,
    g_comanda_maitre: false,
    g_caixa_remover_desconto: false

};

const criarRestricoes = (alteracoes) => ({
    ...restricoesBase,
    ...alteracoes
});

const restricoesPredefinidas = {
    freelancer: criarRestricoes({
        loginSistema: true,
        abrirMesa: true,
        imprimirMesa: true,
        mesaComandarItem: true,
        area_rLoja: false,
    }),
    contratado: criarRestricoes({
        loginSistema: true,
        abrirMesa: true,
        imprimirMesa: true,
        mesaComandarItem: true,
        loginSistemaSempreOn: true,
        area_rLoja: true,
        area_rDelivery: true,
    }),
    atendente: criarRestricoes({
        loginSistema: true,
        abrirMesa: true,
        imprimirMesa: true,
        mesaComandarItem: true,
        loginSistemaSempreOn: true,
        area_rLoja: true,
        area_rDelivery: true,
        area_rLoja: true,
        area_rBar: true,
        area_rDelivery: true,
        area_rGiral: true,
        area_rExterna: true,
        area_rRecepcao: true,
        abrirMesa: true,
    }),
    caixa: criarRestricoes({
        loginSistema: true,
        loginSistemaSempreOn: true,
        imprimirMesa: true,
        mesaComandarItem: true,
        c_caixa_cancelamento: true,
        c_caixa_receber: true,
        c_caixa_desconto: true,
        c_caixa_cobrar: true,
        c_comanda_alterarGorjeta: true,
        c_comanda_RemoverGorjeta: true,
        c_caixa_operador: true,
        m_ComandaTransfere: true,
        m_ComandaDivide: true,
        g_comandaZeradaCancelar: true,
        area_rLoja: true,
        area_rBar: true,
        area_rDelivery: true,
        area_rGiral: true,
        area_rExterna: true,
        area_rRecepcao: true,
        abrirMesa: true,
    }),
    gerente: criarRestricoes({
        loginSistema: true,
        loginSistemaSempreOn: true,
        imprimirMesa: true,
        mesaComandarItem: true,
        c_caixa_cancelamento: true,
        c_caixa_receber: true,
        c_caixa_desconto: true,
        c_caixa_cobrar: true,
        g_caixa_remover_desconto: true,
        c_comanda_alterarGorjeta: true,
        c_comanda_RemoverGorjeta: true,
        g_comanda_maitre: true,
        c_caixa_operador: true,
        g_caixa_operador: true,
        m_ComandaTransfere: true,
        m_ComandaDivide: true,
        m_AreaComandaTransfere: true,
        g_comandaZeradaCancelar: true,
        g_comandaCancelamento: true,
        area_rLoja: true,
        area_rBar: true,
        area_rDelivery: true,
        area_rGiral: true,
        area_rExterna: true,
        area_rRecepcao: true,
        abrirMesa: true,
        g_maitre_abrirMesa: true
    })
};

export default restricoesPredefinidas;