export const CLEAR_SENHA = 'CLEAR_SENHA';
export const SET_SENHA = 'SET_SENHA';
export const ENVIAR_DADOS_USUARIO = 'ENVIAR_DADOS_USUARIO';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const UPDATE_LISTA_USUARIOS = 'UPDATE_LISTA_USUARIOS';